CREATE TABLE ALUMNO(ID VARCHAR(40) PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE);

CREATE TABLE PWD(ID VARCHAR(40) PRIMARY KEY,
    ENCODEDPWD VARCHAR(255) NOT NULL,
    SALTPWD VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(40) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES ALUMNO(ID));


INSERT INTO alumno VALUES
    (1,'Marcel-Alger Vila Gonzalez', 'ma.vila@alumnos.upm.es'),
    (2,'Juan José Herrero Barbosa', 'juan.hbarbosa@alumnos.upm.es'),
    (3,'Irene Enamorado', 'i.enamorado@alumnos.upm.es'),
    (4,'Camilo Macarron Espinosa De Los Monteros', 'c.mararron@alumnos.upm.es'),
    (5,'Gloria Cobo Zambrana', 'gloria.cobo.zambrana@alumnos.upm.es'),
    (6,'Alvaro De Blas Montalvilo', 'alvaro.derojas.maraver@alumnos.upm.es');

INSERT INTO profesor VALUES
(1, 'Luis Fernando Dharo Enriquez', 'luisfernando.dharo@upm.es', '3'),
(2, 'Zarko Gacevic', 'zarko.gacevic@upm.es', '3'),
(3, 'Juan Antonio Lopez Martin', 'juanantonio.lopez@upm.es', '3'),
(4, 'Miguel Angel Sanchez Garcia', 'miguelangel.sanchez@upm.es', '3'),
(5, 'Octavio Nieto-Taladriz Garcia', 'octavio.nietotaladriz@upm.es', '3'),
(6, 'Alvaro De Guzman Fernandez Gonzalez', 'alvarodeguzman.fernandez@upm.es', '3'),
(7, 'Patricia Arroba Garcia', 'p.arroba@upm.es', '3'),
(8, 'Manuel Gil Martin ', 'manuel.gilmartin@upm.es', '3'),
(9, 'Slobodan Bojanic Antonijevic', 'slobodan.bojanic@upm.es', '3'),
(10, 'Teona Mirea', 'teona.mirea@upm.es', '3'),
(11, 'Ricardo De Cordoba Herralde', 'ricardo.cordoba@upm.es', '3'),
(12, 'Maria Jesus Ledesma Carbayo', 'mariajesus.ledesma@upm.es', '3'),
(13, 'Carlos Carreras Vaquer', 'carlos.carreras@upm.es', '3'),
(14, 'Juan Manuel Montero Martinez', 'juanmanuel.montero@upm.es', '3'),
(15, 'Ruben San Segundo Hernandez', 'ruben.sansegundo@upm.es', '3'),
(16, 'Jose Parera Bermudez', 'jose.parera@upm.es', '5'),
(17, 'Miguel Angel García Izquierdo', 'miguelangel.garcia.izquierdo@upm.es', '5'),
(18, 'Jesus Gustavo Cuevas Del Río', 'gustavo.cuevas@upm.es', '5'),
(19, 'Juan Fco. Gomez Mena', 'j.gomez@upm.es', '5'),
(20, 'Juan Miguel Santos Suarez ', 'juan.santos.suarez@upm.es', '5'),
(21, 'Juan Antonio Saras Pazos', 'juanantonio.saras@upm.es', '2'),
(22, 'Gabriel Huecas FernandezToribio', 'gabriel.huecas@upm.es', '2'),
(23, 'Victor Abraham Villagra Gonzalez', 'victor.villagra@upm.es', '2'),
(24, 'Mario Vega Barbas', 'mario.vega@upm.es', '2'),
(25, 'Julian Cabrera Quesada', 'julian.cabrera@upm.es', '5'),
(26, 'Fernando Jaureguizar Nuñez', 'fernando.jaureguizar@upm.es', '5'),
(27, 'Carlos Cuevas Rodriguez ', 'carlos.cuevas@upm.es', '5'),
(28, 'Carlos Roberto Del Blanco Adan', 'carlosrob.delblanco@upm.es', '5'),
(29, 'Francisco Moran Burgos', 'francisco.moran@upm.es', '5'),
(30, 'Luis Salgado Alvarez De Sotomayor', 'luis.salgado@upm.es', '5'),
(31, 'Narciso Garcia Santos', 'narciso.garcia@upm.es', '5'),
(32, 'Luis Bellido Triana', 'luis.bellido@upm.es', '2'),
(33, 'David Fernandez Cambronero', 'david.fernandez@upm.es', '2'),
(34, 'Andres Pedro Gonzalez Lanceros', 'andrespedro.gonzalez@upm.es', '2'),
(35, 'Julio Jose Berrocal Colmenarejo', 'julio.berrocal@upm.es', '2'),
(24, 'Mario Vega Barbas', 'mario.vega@upm.es', '2'),
(37, 'Jose Luis Fernandez Jambrina', 'j.fdez.jambrina@upm.es', '5'),
(38, 'Manuel Sierra Castañer', 'manuel.sierra@upm.es', '5'),
(39, 'Belen Galocha Iraguen ', 'belen.galocha@upm.es', '5'),
(40, 'Pablo Sanchez Olivares', 'pablo.sanchezo@upm.es', '5'),
(41, 'Rodriguez Varela, Fernando', 'f.rodriguezv@upm.es', '5'),
(42, 'Francisco Gonzalez Sanchez', 'francisco.gonzalez.sanchez@upm.es', '7'),
(43, 'Santiago Iglesias Pradas', 's.iglesias@upm.es', '7'),
(44, 'Jose Julian Chaparro Pelaez ', 'julian.chaparro@upm.es', '7'),
(45, 'Felix Jose Pascual Miguel', 'felixjose.pascual@upm.es', '7'),
(46, 'Emiliano Acquila Natale', 'emiliano.acquila@upm.es', '7'),
(47, 'Fernando Fernandez Martinez ', 'fernando.fernandezm@upm. es', '3'),
(48, 'Jose Manuel Pardo Muñoz', 'josemanuel.pardom@upm.es', '3'),
(49, 'Alberto Bosca Mojena', 'alberto.bosca@upm.es', '3'),
(50, 'Juan Jose Gomez Valverde ', 'juanjo.gomez@upm.es', '3'),
(1, 'Luis Fernando Dharo Enriquez', 'luisfernando.dharo@upm.es', '3'),
(52, 'Josue Pagan Ortiz ', 'j.pagan@upm.es', '3'),
(8, 'Manuel Gil Martin ', 'manuel.gilmartin@upm.es', '3'),
(54, 'Benito Artaloytia Encinas', 'benito.artaloytia@upm.es', '1'),
(55, 'Jose Jesus Fraile Ardanuy', 'jesus.fraile.ardanuy@upm.es', '1'),
(56, 'Carlos Del Cañizo Nadal ', 'carlos.canizo@upm.es', '1'),
(57, 'Antonio-p.eduardo Lorenzo Pigueiras', 'antonio.lorenzo@upm.es', '1'),
(58, 'David Jimenez Bermejo', 'david.jimenezb@upm.es', '1'),
(59, 'Alejandro Datas Medina', 'a.datas@upm.es', '1'),
(60, 'Morten Andreas Geday', 'morten.geday@upm.es', '6'),
(61, 'Ignacio Esquivias Moscardo', 'ignacio.esquivias@upm.es', '6'),
(62, 'Miguel Angel Muriel Fernandez', 'm.muriel@upm.es', '6'),
(63, 'Paloma Rodriguez Horche', 'p.rhorche@upm.es', '6'),
(64, 'Francisco Jose Lopez Hernandez', 'francisco.lopez.hernandez@upm.es', '6'),
(65, 'Antonio Perez Serrano ', 'antonio.perez.serrano@upm.es', '6'),
(66, 'Patxi Xabier Quintana Arregui', 'x.quintana@upm.es', '6'),
(67, 'Fernando Ibañez Urzaiz', 'f.ibanez@upm.es', '5'),
(37, 'Jose Luis Fernandez Jambrina', 'j.fdez.jambrina@upm.es', '5'),
(39, 'Belen Galocha Iraguen ', 'belen.galocha@upm.es', '5'),
(70, 'Javier Gismero Menoyo', 'javier.gismero@upm.es', '5'),
(71, 'Jose Ignacio Alonso Montes', 'joseignacio.alonso@upm.es', '5'),
(72, 'Carlos Gustavo Perez Moreno', 'carlosgustavo.perez@upm.es', '5'),
(73, 'Jose Manuel Fernandez Gonzalez', 'josemanuel.fernandez.gonzalez@upm.es', '5'),
(74, 'Miguel Alejandro Salas Natera', 'miguel.salas@upm.es', '5'),
(75, 'Adrian Tamayo Dominguez', 'a.tamayo@upm.es', '5'),
(76, 'Pablo Sanchez Olivares ', 'pablo.sanchezo@upm.es', '5'),
(77, 'Felix Perez Martinez ', 'felix.perez.martinez@upm.es', '5'),
(78, 'Juan Quemada Vives', 'juan.quemada@upm.es', '2'),
(79, 'Santiago Pavon Gomez ', 'santiago.pavon@upm.es', '2'),
(80, 'Joaquin Luciano Salvachua Rodriguez', 'joaquin.salvachua@upm.es', '2'),
(81, 'Enrique Barra Arias', 'enrique.barra@upm.es', '2'),
(82, 'Juan Fernando Sanchez Rada', 'jf.sanchez@upm.es', '2'),
(83, 'Alvaro Alonso Gonzalez ', 'alvaro.alonso@upm.es', '2'),
(84, 'Lopez Pernas, Sonsoles', 'sonsoles.lopez.pernas@upm.es', '2'),
(85, 'Angel Fernandez Del Campo', 'angel.fernandez.delcampo@upm.es', '2'),
(86, 'Carlos Miguel Nieto', 'carlos.miguel@upm.es', '2'),
(87, 'Francisco Faustino Lázaro Anguis', 'ff.lazaro@upm.es', '2'),
(88, 'Victor Abraham Villagrá Gonzalez ', 'victor.villagra@upm.es', '2'),
(89, 'Xavier Andres Larriva Novo', 'xavier.larriva.novo@upm.es', '2'),
(90, 'Diego Rivera Pinto', 'diego.rivera@upm.es', '2'),
(35, 'Julio Jose Berrocal Colmenarejo', 'julio.berrocal@upm.es', '2'),
(92, 'Manuel Alvarez-Campana Fdez.-Corredor', 'manuel.alvarez-campana@upm.es', '2'),
(93, 'Enrique Vazquez Gallo', 'enrique.vazquez@upm.es', '2'),
(94, 'Santiago Pavon Gomez', 'santiago.pavon@upm.es', '2'),
(95, 'Enrique Barra Arias ', 'enrique.barra@upm.es', '2'),
(96, 'Alvaro Alonso Gonzalez', 'alvaro.alonso@upm.es', '2'),
(97, 'Sonsoles Lopez Pernas ', 'sonsoles.lopez.pernas@upm.es', '2'),
(98, 'Alejandro Antonio Alonso Muñoz', 'alejandro.alonso@upm.es', '2'),
(99, 'Amalio Francisco Nieto Serrano', 'amalio.nieto@upm.es', '2'),
(33, 'David Fernandez Cambronero', 'david.fernandez@upm.es', '2'),
(80, 'Joaquin Luciano Salvachua Rodriguez', 'joaquin.salvachua@upm.es', '2'),
(102, 'Carlos Miguel Nieto ', 'carlos.miguel@upm.es', '2'),
(103, 'Antonio F. Martinez Mas', 'antonio.martinez.mas@upm.es', '2'),
(34, 'Andres Pedro Gonzalez Lanceros', 'andrespedro.gonzalez@upm.es', '2'),
(105, 'Luis Enrique García Fernandez', 'luisenrique.garciaf@upm.es', '2'),
(106, 'Juan Carlos Yelmo Garcia', 'juancarlos.yelmo@upm.es', '2'),
(107, 'Juan Carlos Dueñas Lopez ', 'juancarlos.duenas@upm.es', '2'),
(108, 'Jose Maria Del Álamo Ramiro', 'jm.delalamo@upm.es', '2'),
(109, 'Félix Cuadrado', 'felix.cuadrado@upm.es', '2'),

INSERT INTO Subject VALUES
(1, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '1', '1', '3'),
(2, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '2', '1', '3'),
(3, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '3', '1', '3'),
(4, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '4', '1', '3'),
(5, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '5', '1', '3'),
(6, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '6', '1', '3'),
(7, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '7', '1', '3'),
(8, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '8', '1', '3'),
(9, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '9', '1', '3'),
(10, 'CIRCUITOS ELECTRÓNICOS', 'CELT', '3', '10', '1', '3'),
(11, 'SISTEMAS DIGITALES I', 'SDG1', '3', '11', '1', '3'),
(12, 'SISTEMAS DIGITALES I', 'SDG1', '3', '12', '1', '3'),
(13, 'SISTEMAS DIGITALES I', 'SDG1', '3', '13', '1', '3'),
(14, 'SISTEMAS DIGITALES I', 'SDG1', '3', '14', '1', '3'),
(15, 'SISTEMAS DIGITALES I', 'SDG1', '3', '15', '1', '3'),
(16, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TDSÑ', '5', '16', '1', '3'),
(17, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TDSÑ', '5', '17', '1', '3'),
(18, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TDSÑ', '5', '18', '1', '3'),
(19, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TDSÑ', '5', '19', '1', '3'),
(20, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TDSÑ', '5', '20', '1', '3'),
(21, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TINF', '2', '21', '1', '3'),
(22, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TINF', '2', '22', '1', '3'),
(23, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TINF', '2', '23', '1', '3'),
(24, 'TRATAMIENTO DIGITAL DE SEÑALES', 'TINF', '2', '24', '1', '3'),
(25, 'SISTEMAS DE TRANSMISIÓN', 'STRA', '5', '25', '1', '3'),
(26, 'SISTEMAS DE TRANSMISIÓN', 'STRA', '5', '26', '1', '3'),
(27, 'SISTEMAS DE TRANSMISIÓN', 'STRA', '5', '27', '1', '3'),
(28, 'SISTEMAS DE TRANSMISIÓN', 'STRA', '5', '28', '1', '3'),
(29, 'SISTEMAS DE TRANSMISIÓN', 'STRA', '5', '29', '1', '3'),
(30, 'SISTEMAS DE TRANSMISIÓN', 'STRA', '5', '30', '1', '3'),
(31, 'SISTEMAS DE TRANSMISIÓN', 'STRA', '5', '31', '1', '3'),
(32, 'REDES DE ORDENADORES', 'RDOR', '2', '32', '1', '3'),
(33, 'REDES DE ORDENADORES', 'RDOR', '2', '33', '1', '3'),
(34, 'REDES DE ORDENADORES', 'RDOR', '2', '34', '1', '3'),
(35, 'REDES DE ORDENADORES', 'RDOR', '2', '35', '1', '3'),
(36, 'REDES DE ORDENADORES', 'RDOR', '2', '24', '1', '3'),
(37, 'RADIACIÓN Y PROPAGACIÓN', 'RDPR', '5', '37', '1', '3'),
(38, 'RADIACIÓN Y PROPAGACIÓN', 'RDPR', '5', '38', '1', '3'),
(39, 'RADIACIÓN Y PROPAGACIÓN', 'RDPR', '5', '39', '1', '3'),
(40, 'RADIACIÓN Y PROPAGACIÓN', 'RDPR', '5', '5', '1', '3'),
(41, 'RADIACIÓN Y PROPAGACIÓN', 'RDPR', '5', '41', '1', '3'),
(42, 'ORGANIZACIÓN DE EMPRESAS', 'ORGE', '7', '42', '1', '3'),
(43, 'ORGANIZACIÓN DE EMPRESAS', 'ORGE', '7', '43', '1', '3'),
(44, 'ORGANIZACIÓN DE EMPRESAS', 'ORGE', '7', '44', '1', '3'),
(45, 'ORGANIZACIÓN DE EMPRESAS', 'ORGE', '7', '45', '1', '3'),
(46, 'ORGANIZACIÓN DE EMPRESAS', 'ORGE', '7', '46', '1', '3'),
(47, 'SISTEMAS DIGITALES II', 'SDG2', '3', '47', '1', '3'),
(48, 'SISTEMAS DIGITALES II', 'SDG2', '3', '48', '1', '3'),
(49, 'SISTEMAS DIGITALES II', 'SDG2', '3', '49', '1', '3'),
(50, 'SISTEMAS DIGITALES II', 'SDG2', '3', '50', '1', '3'),
(51, 'SISTEMAS DIGITALES II', 'SDG2', '3', '1', '1', '3'),
(52, 'SISTEMAS DIGITALES II', 'SDG2', '3', '52', '1', '3'),
(53, 'SISTEMAS DIGITALES II', 'SDG2', '3', '8', '1', '3'),
(54, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '54', '1', '3'),
(55, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '55', '1', '3'),
(56, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '56', '1', '3'),
(57, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '57', '1', '3'),
(58, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '58', '1', '3'),
(59, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '59', '1', '3'),
(60, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '60', '1', '3'),
(61, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '61', '1', '3'),
(62, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '62', '1', '3'),
(63, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '63', '1', '3'),
(64, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '64', '1', '3'),
(65, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '65', '1', '3'),
(66, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '66', '1', '3'),
(67, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '67', '1', '3'),
(68, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '37', '1', '3'),
(69, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '39', '1', '3'),
(70, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '70', '1', '3'),
(71, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '71', '1', '3'),
(72, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '72', '1', '3'),
(73, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '73', '1', '3'),
(74, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '74', '1', '3'),
(75, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '75', '1', '3'),
(76, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '40', '1', '3'),
(77, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '77', '1', '3'),
(78, 'COMPUTACIÓN EN RED', 'CORE', '2', '78', '1', '3'),
(79, 'COMPUTACIÓN EN RED', 'CORE', '2', '94', '1', '3'),
(80, 'COMPUTACIÓN EN RED', 'CORE', '2', '80', '1', '3'),
(81, 'COMPUTACIÓN EN RED', 'CORE', '2', '81', '1', '3'),
(82, 'COMPUTACIÓN EN RED', 'CORE', '2', '82', '1', '3'),
(83, 'COMPUTACIÓN EN RED', 'CORE', '2', '83', '1', '3'),
(84, 'COMPUTACIÓN EN RED', 'CORE', '2', '84', '1', '3'),
(85, 'REDES CORPORATIVAS', 'RECO', '2', '85', '1', '4'),
(86, 'REDES CORPORATIVAS', 'RECO', '2', '86', '1', '4'),
(87, 'SEGURIDAD EN SISTEMAS Y REDES DE TELECOMUNICACIÓN', 'SEGU', '2', '87', '1', '4'),
(88, 'SEGURIDAD EN SISTEMAS Y REDES DE TELECOMUNICACIÓN', 'SEGU', '2', '23', '1', '4'),
(89, 'SEGURIDAD EN SISTEMAS Y REDES DE TELECOMUNICACIÓN', 'SEGU', '2', '89', '1', '4'),
(90, 'SEGURIDAD EN SISTEMAS Y REDES DE TELECOMUNICACIÓN', 'SEGU', '2', '90', '1', '4'),
(91, 'REDES DE COMUNICACIONES MÓVILES', 'RCMO', '2', '35', '1', '4'),
(92, 'REDES DE COMUNICACIONES MÓVILES', 'RCMO', '2', '92', '1', '4'),
(93, 'REDES DE COMUNICACIONES MÓVILES', 'RCMO', '2', '93', '1', '4'),
(94, 'INGENIERÍA WEB', 'IWEB', '2', '94', '1', '4'),
(95, 'INGENIERÍA WEB', 'IWEB', '2', '95', '1', '4'),
(96, 'INGENIERÍA WEB', 'IWEB', '2', '83', '1', '4'),
(97, 'INGENIERÍA WEB', 'IWEB', '2', '84', '1', '4'),
(98, 'CENTROS DE DATOS Y DE PROVISIÓN DE SERVICIOS', 'CDPS', '2', '98', '1', '4'),
(99, 'CENTROS DE DATOS Y DE PROVISIÓN DE SERVICIOS', 'CDPS', '2', '99', '1', '4'),
(100, 'CENTROS DE DATOS Y DE PROVISIÓN DE SERVICIOS', 'CDPS', '2', '33', '1', '4'),
(101, 'CENTROS DE DATOS Y DE PROVISIÓN DE SERVICIOS', 'CDPS', '2', '80', '1', '4'),
(102, 'REDES Y SERVICIOS DE RADIO', 'RSRD', '2', '86', '1', '4'),
(103, 'REDES Y SERVICIOS DE RADIO', 'RSRD', '2', '103', '1', '4'),
(104, 'DIMENSIONADO Y OPERACIÓN DE REDES', 'DORE', '2', '34', '1', '4'),
(105, 'DIMENSIONADO Y OPERACIÓN DE REDES', 'DORE', '2', '105', '1', '4'),
(106, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '106', '1', '4'),
(107, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '107', '1', '4'),
(108, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '108', '1', '4'),
(109, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '109', '1', '4'),
(110, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '37', '4', '3'),
(111, 'ORGANIZACIÓN DE EMPRESAS', 'ORGE', '7', '42', '4', '3'),
(112, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '106', '4', '4'),
(113, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '107', '4', '4'),
(114, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '108', '4', '4'),
(115, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '109', '4', '4'),
(116, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '106', '3', '4'),
(117, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '107', '3', '4'),
(118, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '108', '3', '4'),
(119, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '109', '3', '4'),
(120, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '106', '2', '4'),
(121, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '107', '2', '4'),
(122, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '108', '2', '4'),
(123, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '109', '2', '4'),
(124, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '106', '5', '4'),
(124, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '107', '5', '4'),
(126, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '108', '5', '4'),
(127, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '109', '5', '4'),
(128, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '106', '6', '4'),
(129, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '107', '6', '4'),
(130, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '108', '6', '4'),
(131, 'INGENIERÍA DE SISTEMAS Y SERVICIOS TELEMÁTICOS', 'ISST', '2', '109', '6', '4'),
(132, 'COMPUTACIÓN EN RED', 'CORE', '2', '81', '4', '3'),
(133, 'DIMENSIONADO Y OPERACIÓN DE REDES', 'DORE', '2', '105', '4', '4'),
(134, 'REDES Y SERVICIOS DE RADIO', 'RSRD', '2', '103', '4', '4'),
(135, 'REDES Y SERVICIOS DE RADIO', 'RSRD', '2', '103', '4', '5'),
(136, 'DIMENSIONADO Y OPERACIÓN DE REDES', 'DORE', '2', '105', '5', '4'),
(137, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '37', '3', '3'),
(138, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '57', '3', '3'),
(139, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '58', '3', '3'),
(140, 'DIMENSIONADO Y OPERACIÓN DE REDES', 'DORE', '2', '34', '3', '4'),
(141, 'DIMENSIONADO Y OPERACIÓN DE REDES', 'DORE', '2', '105', '3', '4'),
(142, 'REDES Y SERVICIOS DE RADIO', 'RSRD', '2', '103', '6', '4'),
(143, 'REDES Y SERVICIOS DE RADIO', 'RSRD', '2', '103', '6', '5'),
(144, 'COMUNICACIONES ÓPTICAS', 'COPT', '6', '61', '6', '3'),
(145, 'SISTEMAS DIGITALES II', 'SDG2', '3', '47', '6', '3'),
(146, 'SISTEMAS DIGITALES II', 'SDG2', '3', '48', '6', '3'),
(147, 'SISTEMAS DIGITALES II', 'SDG2', '3', '49', '6', '3'),
(148, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '56', '6', '3'),
(149, 'SISTEMAS DE ENERGÍA', 'ENRG', '1', '57', '6', '3'),
(69, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '39', '6', '3'),
(70, 'ELECTRÓNICA DE COMUNICACIONES', 'ECOM', '5', '70', '6', '3'),


INSERT INTO preguntaencuesta VALUES
    ('qa1','Las actividades de la asignatura se reparten de manera uniforme durante el semestre.','texto'),
    ('qa2','En el desarrollo de esta asignatura no hay solapamientos con los contenidos de otras, ni repeticiones innecesarias.','texto'),
    ('qa3','Se han coordinado adecuadamente las clases teóricas y prácticas previstas en el programa.','texto'),
    ('qa4','Las prácticas de laboratorio y las actividades complementarias (conferencias, seminarios, visitas de estudio, etc.…) ayudan a la comprensión de la asignatura.','texto'),
    ('qa5', 'Los métodos utilizados para mi evaluación (exámenes, memorias de prácticas, trabajos individuales o de grupo, etc.) son adecuados para el tipo de actividades y contenidos de la asignatura.','texto'),
    ('qa6','La carga de trabajo que comprende esta asignatura es adecuada para el número de créditos que tiene asignados.','texto'),
    ('qa7','Los conocimientos adquiridos en esta asignatura son importantes para mi actividad profesional.','texto'),
    ('qa8','En general, estoy satisfecho con el desarrollo de la asignatura.','texto'),
    ('qp1','El profesor cumple con su horario de clase establecido.','texto');

INSERT INTO traits VALUES
    ('t01','cercano'),
    ('t02','impuntual'),
    ('t03','accesible para tutorías'),
    ('t04','clases amenas'),
    ('t05','desorganizado'),
    ('t06','se prepara las clases'),
    ('t07','se pasa de la hora'),
    ('t08','clases poco dinámicas'),
    ('t09','buenos apuntes'),
    ('t10','poco material de estudio');
